### ISSUE TITLE
Binningtransformation

### ISSUE THREAD

**Issue by nikkisingh111333** [oracle/tribuo#103]
Hey ,i m trying to figuring out binning using binningtransformation how can i integrate it with transformerMao and turn my numeric feature into bins (numeric) i have read the docs but dont know where to start? guide me up please

**Comment by Craigacp** [comment]
Please stop using the bug report issue template (or equivalently assigning the bug label) for documentation or other questions. There are labels for questions and docs, which help us track the different kinds of issues.

To apply a `BinningTransformation` to each feature separately do this:

```java
var binTransform = BinningTransformation.equalWidth(10);
var transformationMap = new TransformationMap(Collections.singletonList(binTransform));
```

This will bin every feature into 10 equal width bins. You can use the `equalFreq` or `stdDevs` static methods to generate a binning transform which uses those algorithms. The different algorithms are described in the [javadoc](https://tribuo.org/learn/4.0/javadoc/org/tribuo/transform/transformations/BinningTransformation.html). If you want to bin a subset of the features then you can supply a map containing appropriate regexes and the relevant transforms to the `TransformationMap`.

**Comment by nikkisingh111333** [comment]
okk i got it thanks for the quick support.
