### ISSUE TITLE
Update website links to 4.1, etc.

### ISSUE THREAD

**Issue by nezda** [oracle/tribuo#145]
Update the website links to the new 4.1 content
- [ ] https://tribuo.org/learn/4.1/tutorials/ is 404
- [ ] artifacts still 4.0.2, e.g., 
![image](https://user-images.githubusercontent.com/179091/120443310-1f994000-c34c-11eb-9bdd-c3836597a330.png)
- [ ] consider adding a "What's New in 4.1" blurb
- [ ] tell GitHub the project is Apache 2.0 licensed https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository so it looks like this
![image](https://user-images.githubusercontent.com/179091/120444455-3f7d3380-c34d-11eb-80ed-c827e14f6a27.png)

- [ ] consider enabling GitHub Discussions for trivial pseudo-issues like this: it's in https://github.com/nezda/yawni/settings on my project (Projects also looks pretty cool)

**Comment by Craigacp** [comment]
We're working on the website, it's nearly done (https://github.com/oracle/tribuo-site/tree/4.1-update), however it won't go live until the binaries are on maven central which will take a little while longer.

Github's license detection is confused by our third_party_licenses.txt file, and can't be overridden (nor can we change the third party licenses filename).

We're still thinking about using discussions, and haven't come to a conclusion yet.

**Comment by Craigacp** [comment]
The website has now been updated and v4.1.0 binaries are available on Maven Central.
