### ISSUE TITLE
Can LibSVMClassificationTrainer and LIMEExplanation be used to extract meaningful features from SVM?

### ISSUE THREAD

**Issue by lukaszbachman** [oracle/tribuo#155]
I would like to use SVM for classification, then later use LIME to explain what the model thinks in a human friendly way.

Unfortunately, it looks like `LIMEText` expects a class implementing `SparseTrainer` which `LibSVMClassificationTrainer` does not do. I'm wondering if there is a chance to make it work somehow? I'm new to the API (started exploring it yesterday), so maybe I'm missing a concept which would come with more experience.

**Is your question about a specific Tribuo class?**
`LIMEText, SparseTrainer, LibSVMClassificationTrainer`

**System details**
- Tribuo version: 4.1.0
- Java version: 11

**Comment by lukaszbachman** [comment]
After getting more acquainted with unit tests, I came to a realization that I made a wrong assumption that LIME needs to use the same trainer as used for building the original model. It's actually the opposite, there is no requirement as such. Therefore it's completely fine to use SVM to create a model and later use any sparse trainer to explain it, like this:

```
// ...
var trainer = new LibSVMClassificationTrainer(params);
Model<Label> model = trainer.train(trainData);
// ...
var sparseTrainer = new CARTJointRegressionTrainer(4, true);
var lime = new LIMEColumnar(new SplittableRandom(1), model, sparseTrainer, 5000, rowProcessor, tokenizer);
LIMEExplanation explain = lime.explain(trainData.getExample(0));
explain.getModel().getActiveFeatures();
```

**Comment by Craigacp** [comment]
Yep the LIME requirement is that the explaining model is sparse not the model that's being explained. This is actually more expressive than the original LIME paper which only used l1 regularised linear models as the explaining model, in Tribuo you can use trees too.
