### ISSUE TITLE
How to get json example of a configurable class?

### ISSUE THREAD

**Issue by C-Compton** [oracle/tribuo#173]
I was able to find this example in the guides/tutorials on how to inspect a configurable class. 
```
$ java -cp <path-to-jars-including-olcut-core> com.oracle.labs.mlrg.olcut.config.DescribeConfigurable -n <class-name> -o -e xml
```

How can I get a json example instead of xml? I've searched but cannot find any documentation.  References in the documentation have `--config-file-format com.oracle.labs.mlrg.olcut.config.json.JsonConfigFactory`, but `--config-file-format` is only a valid argument for `ConfigurationManager` class and not `DescribeConfigurable`.

**Comment by Craigacp** [comment]
Ahhh. That's an oversight on our part. We turned off the config file arguments in `DescribeConfigurable` a few years ago but that also removed the config file factory option which you use to add extra config support so we need to add that back to `DescribeOptions`. I'll fix that over in OLCUT for the next release.

In the meantime you can call `DescribeConfigurable.writeExampleConfig` directly from jshell after calling `ConfigurationManager.addFileFormatFactory()` with an instance of `com.oracle.labs.mlrg.olcut.config.json.JsonConfigFactory`. It'll write the config to the supplied output stream. I'll add javadoc for all the public methods in `DescribeConfigurable` when we fix the other issue.

**Comment by Craigacp** [comment]
It'll be fixed when https://github.com/oracle/olcut/pull/39 is merged into OLCUT.

**Comment by Craigacp** [comment]
It's merged in now, so if you prepend `olcut-core-5.1.7-SNAPSHOT.jar` to your classpath before running `DescribeConfigurable` then you should be able to generate json or edn configs. Protobuf support is coming in the next release too, both in text and binary forms.

**Comment by C-Compton** [comment]
Thank you. I will give it a try and report back.

**Comment by C-Compton** [comment]
Still not able to generate a JSON configuration.
```
➜  ~ java -cp /Users/ccompton/.gradle/caches/modules-2/files-2.1/org.tribuo/tribuo-data/4.1.0/b48254b8dea9a169e2e244888d40aa82cfe4496b/tribuo-data-4.1.0.jar:/Users/ccompton/tmp/olcut/olcut-core/target/olcut-core-5.1.7-SNAPSHOT.jar:/Users/ccompton/tmp/olcut/olcut-config-json/target/olcut-config-json-5.1.7-SNAPSHOT.jar  com.oracle.labs.mlrg.olcut.config.DescribeConfigurable -n org.tribuo.data.sql.SQLDBConfig -o -e json
Class: org.tribuo.data.sql.SQLDBConfig

Field Name       Type                                             Mandatory Redact Default Description
connectionString java.lang.String                                 false     false          Connection string, including host, port and db.
db               java.lang.String                                 false     false          Database name.
fetchSize        int                                              false     false  1000    Size of batches to fetch from DB for queries
host             java.lang.String                                 false     false          Hostname of the database machine.
password         java.lang.String                                 false     true           Database password.
port             java.lang.String                                 false     false          Port number.
propMap          java.util.Map<java.lang.String,java.lang.String> false     false  {}      Properties to pass to java.sql.DriverManager, username and password will be removed and populated to their fields. If specified both on the map and in the fields, the fields will be used
username         java.lang.String                                 false     true           Database username.

Exception in thread "main" java.lang.IllegalArgumentException: No format factory found for extension 'json'
	at com.oracle.labs.mlrg.olcut.config.DescribeConfigurable.writeExampleConfig(DescribeConfigurable.java:399)
	at com.oracle.labs.mlrg.olcut.config.DescribeConfigurable.main(DescribeConfigurable.java:545)
➜  ~ 
```

**Comment by Craigacp** [comment]
You need to add `--config-file-formats com.oracle.labs.mlrg.olcut.config.json.JsonConfigFactory` to the arguments and the jackson jars to your class path. The config factories should really be SPIs but we've not switched them over to that yet so you still need to tell OLCUT that they exist.

**Comment by C-Compton** [comment]
Perfect. Thank you!
