### ISSUE TITLE
How to properly set `trainerType` in a config file?

### ISSUE THREAD

**Issue by C-Compton** [oracle/tribuo#174]
I'm trying to set up a configuration file for a trainer based on the example configuration for the class. 

```
{
  "config" : {
    "components" : [ {
      "name" : "example",
      "type" : "org.tribuo.classification.liblinear.LibLinearClassificationTrainer",
      "export" : "false",
      "import" : "false",
      "properties" : {
        "epsilon" : "0.0",
        "labelWeights" : {
          "mapKey" : "java.lang.Float-instance"
        },
        "maxIterations" : "0",
        "cost" : "0.0",
        "terminationCriterion" : "0.0",
        "trainerType" : "LibLinearType-instance"
      }
    } ]
  }
}
```

The `trainerType` takes `org.tribuo.common.liblinear.LibLinearType`, and defaults to `org.tribuo.classification.liblinear.LinearClassificationType@46daef40`. What would I put in place of the default if I want to use a different algorithm? 

I've tried 
`"trainerType" : "org.tribuo.classification.liblinear.LinearClassificationType.LinearType@L1R_L2LOSS_SVC"`
`"trainerType" : "org.tribuo.classification.liblinear.LinearClassificationType.LinearType.L1R_L2LOSS_SVC"`
`"trainerType" : "org.tribuo.classification.liblinear.LinearClassificationType.L1R_L2LOSS_SVC"`
`"trainerType" : "org.tribuo.classification.liblinear.LinearClassificationType.LinearType"`
`"trainerType" : "org.tribuo.classification.liblinear.LinearClassificationType"`

I also tried printing out the provenance of the default values for this trainer and copying the value for `trainerType` from the output into the config file. 

All of which resulted in a `Failed to find component` error such as below.
```
Exception in thread "main" Property Exception component:'org.tribuo.classification.liblinear.LinearClassificationType.LinearType@L1R_L2LOSS_SVC' - Failed to find component.
com.oracle.labs.mlrg.olcut.config.PropertyException: Component: org.tribuo.classification.liblinear.LinearClassificationType.LinearType@L1R_L2LOSS_SVC, Failed to find component.
	at com.oracle.labs.mlrg.olcut.config.ConfigurationManager.innerLookup(ConfigurationManager.java:1372)
```

**Comment by Craigacp** [comment]
Two things there, first it looks like we're missing a `toString` on `LinearClassificationType` and presumably the other similar classes in LibLinear and LibSVM. That's easy to fix. Second the way the `LinearClassificationType` interacts with the config system is a little ugly due to the type constraints. What you need to do is add another component to the config file which contains a single field with the enum value.

```json 
  "config" : {
    "components" : [ {
      "name" : "liblinear",
      "type" : "org.tribuo.classification.liblinear.LibLinearClassificationTrainer",
      "export" : "false",
      "import" : "false",
      "properties" : {
        "cost" : "1.0",
        "terminationCriterion" : "0.1",
        "trainerType" : "liblinear-algorithm"
      }
    }, {
      "name" : "liblinear-algorithm",
      "type" : "org.tribuo.classification.liblinear.LinearClassificationType",
      "export" : "false",
      "import" : "false",
      "properties" : {
        "type" : "L2R_L1LOSS_SVC_DUAL"
      }
    }, {
      "name" : "label-factory",
      "type" : "org.tribuo.classification.LabelFactory",
      "export" : "false",
      "import" : "false"
    } ]
  }
}
```

I generated this from the example xml config using the following jshell snippet:

```java
jshell> import com.oracle.labs.mlrg.olcut.config.*

jshell> import com.oracle.labs.mlrg.olcut.config.json.*

jshell> ConfigurationManager.addFileFormatFactory(new JsonConfigFactory())

jshell> var cm = new ConfigurationManager("Tribuo/Classification/LibLinear/configs/liblinear-example.xml")
cm ==> com.oracle.labs.mlrg.olcut.config.ConfigurationManager@7ad7775b

jshell> var baos = new ByteArrayOutputStream()
baos ==> 

jshell> cm.save(baos,"json",true)
```
and then you can look at the byte array output stream (or alternatively you can just save the configuration to a file using one of the other overloads of `ConfigurationManager.save`.

**Comment by C-Compton** [comment]
Thank you!
