### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by asad-awadia** [oracle/tribuo#180]
Is there any documentation on what objects in tribuo are thread safe?

For example is a model on which I call predict thread safe?

**Comment by asad-awadia** [comment]
@Craigacp

**Comment by Craigacp** [comment]
`Model.predict` is thread safe. If it's not concurrent the predict method is marked `synchronized`. `Trainer.train` is also thread safe and if the native library is not concurrent then it is also marked `synchronized`.

If you find an instance of predict or train which is not thread-safe or marked synchronized then that's a bug and we'll fix it.

The data side of things is not thread safe if you have concurrent modification operations. Most datasources are thread safe as they mutate all their state on construction, but `org.tribuo.columnar.ColumnarDataSource` instances it's `RowProcessor` on iteration and that can cause confusing behaviour. In general you should create a data source once, pass it into a dataset and then the dataset can be read from concurrently. Transforming a dataset is not thread safe with respect to other accesses.

**Comment by asad-awadia** [comment]
thank you!
