### ISSUE TITLE
K-Fold Cross Validation.

### ISSUE THREAD

**Issue by Mohammed-Ryiad-Eiadeh** [oracle/tribuo#218]
Once using the K-Fold Cross Validation, how to get the values of the performance measurements like TP, FP, ...etc.?

**Comment by Craigacp** [comment]
We should add an overload to `EvaluationAggregator.summarize` to make this easier, but the current way to do it is:

```java
CrossValidation<Label> cv = new CrossValidation(...);
List<Pair<LabelEvaluation,Model<Label>>> evaluation = cv.evaluate();
Map<MetricID<T>,DescriptiveStats> metrics = EvaluationAggregator.summarize(evaluation.stream().map(p -> p.getA()).collect(Collectors.toList()));
```

Then you can inspect the metrics map for each metric you want, and you'll get back a stats object with mean, std dev, max and min.
