### ISSUE TITLE
Embedding the data headers in .CSV files and others

### ISSUE THREAD

**Issue by Mohammed-Ryiad-Eiadeh** [oracle/tribuo#240]
greeting.  is there any way to represent .CSV file in tribuo with the header (e.g., features and the label), since it will be a good feature if we can decide whether to embed the data header or not by a parameter (e,g., type true if the file contains header or false if not), i think it will be a good one when working with other libraries like tablesaw which is very useful to manipulate data like dropping columns,  add rows and many others. When reading a large .CSV file, i used to separate the header in other .CSV file and read it and break it into tokens in an array of string, but i think its more propriate to read the header and data with out writing the header as i did or manually.

**Comment by Craigacp** [comment]
The simple `CSVLoader` lets you specify the headers if they aren't present in the file, though it will use all columns as part of the dataset. If you need to only select a subset of the columns, or apply more complicated processing then you can use `CSVDataSource`, and specify the headers using [this constructor](https://tribuo.org/learn/4.2/javadoc/org/tribuo/data/csv/CSVDataSource.html#%3Cinit%3E(java.net.URI,org.tribuo.data.columnar.RowProcessor,boolean,char,char,java.util.List)). The [columnar data tutorial](https://tribuo.org/learn/4.2/tutorials/columnar-tribuo-v4.html) covers the features of our csv & json loading package in some detail, showing how to control how each column is featurised and how to add extra metadata to each example from specific columns.

**Comment by Mohammed-Ryiad-Eiadeh** [comment]
I will check that, thanks for the fast response.
