### ISSUE TITLE
RowProcessor issue

### ISSUE THREAD

**Issue by Mohammed-Ryiad-Eiadeh** [oracle/tribuo#251]
After construction 'var Fprocessor = new HashMap<String, FieldProcessor>();
                              Fprocessor.put("feature.*", new DoubleFieldProcessor("feature.*"));
                              Fprocessor.put("algo.*", new DoubleFieldProcessor("algo.*"));'
it gives my a warning like ' WARNING: Row 949 empty of features, omitting'.
but when i use the exact field name (the name of the feature), it works fine.
i have checked the regular expression .*, but i don't know what is the problem

**Is your question about a specific ML algorithm or approach?**
Please describe the ML algorithm, with appropriate links or references.

**Is your question about a specific Tribuo class?**
List the classes involved.

**System details**
- Tribuo version : Tribuo-4.2.1
- Java version (if appropriate) : JDK 17 (corretto)
- OS/Architecture (if appropriate) : windows 11

**Additional context**
Add any other context or screenshots about the question
![Screenshot (9)](https://user-images.githubusercontent.com/93108547/179132765-6de8b988-4989-4d01-bfa5-ea3237901f48.png)

**Comment by Craigacp** [comment]
If you want to use a regex to generate the field processors at loading time then you're supplying the `Mapping` argument to the wrong constructor. You need to use this one:
```java
    public RowProcessor(List<FieldExtractor<?>> metadataExtractors, FieldExtractor<Float> weightExtractor,
        ResponseProcessor<T> responseProcessor, Map<String,FieldProcessor> fieldProcessorMap,
        Map<String,FieldProcessor> regexMappingProcessors, Set<FeatureProcessor> featureProcessors)
```
Then pass in `Mapping` to `regexMappingProcessors` and supplying `Collections.emptyMap()` to `fieldProcessorMap`. `RowProcessor` really needs to use a builder to construct it as it's rather complicated, but we haven't got around to designing auto-generated builder support for `Configurable` classes, and didn't want to add one-off builders to classes. We should probably revisit that decision in the case of `RowProcessor` though as it's really very confusing.

**Comment by Mohammed-Ryiad-Eiadeh** [comment]
well, now everything is work as it should be.
i hope you will keep evolve Tribuo library and deliver such strong models like FMtrainer.
i think of building K-Medoid Clustering algorithm and ask you if it is suit for Tribuo

**Comment by Mohammed-Ryiad-Eiadeh** [comment]
sounds well, so i should understand K-Means model in Tribuo first.
sounds very well.
