### ISSUE TITLE
CSVReaderHeaderAware readmap issue

### ISSUE THREAD

**Issue by nsankar** [oracle/tribuo#260]
The CSVReaderHeaderAware reader.readmap() function when reading a CSV file seems to have issues when the header names have either longer text or something related to it.

Here are the details.
Below is the CSV reader code snippet I am using
```
String file_path = <local csv path >;
String csv_path = file_path_train.replace("\\", "/");
Map<String, FieldProcessor> regexMappingProcessors = new HashMap<>(); 
var reader = new CSVReaderHeaderAware(new FileReader(csv_path));
var record = reader.readMap();  
```
For the HDBSCAN model training, I used two csv files . Both the files are attached herewith.   
When I read the 1st CSV file "synthetic_data_training.csv" that has 113 columns, using the above cited code info, I could read the file and build the hdbscan model without any issues.

Then when I used another training dataset attached herewith "synthetic_data_training_resptime_70_30_derived.csv"  which has 54 columns with all data entries, I got the following error. As you can see , all the header columns are present in the file. I suspect the reader perhaps did not consider some of the header text and therefore reports that the expected is 48 , but in actual the column size in dataset is 54 ?.
Could this be due to any considerations in the pattern or length of the header text?

```
Exception in thread "main" java.io.IOException: Error on record number 2: The number of data elements is not the same as the number of header elements. Expected 48, found 54.
	at com.opencsv.CSVReaderHeaderAware.readMap(CSVReaderHeaderAware.java:117)
	at org.tribuo.clustering.hdbscan.NewTest.main(NewTest.java:345)
```
The issue is pointing to var record = reader.readMap();  line

[synthetic_data_training.csv
[synthetic_data_training_resptime_70_30_derived.csv](https://github.com/oracle/tribuo/files/9301377/synthetic_data_training_resptime_70_30_derived.csv)
](https://github.com/oracle/tribuo/files/9301349/synthetic_data_training.csv)

Thanks in advance.

**Comment by nsankar** [comment]
@Craigacp  Got it. I realized that CSVReaderHeaderAware is from OpenCSV. The reason I had used it if you see the code block below is to read all the headers by looping the readMap.  
(i.e. instead of manually inserting all the columns like
  regexMappingProcessors.put("Feature1", new DoubleFieldProcessor("Feature1"));)

After this, I used the CSVDataSource.

Now, Instead of the above, How can I read the CSV file - i.e.  all its headers using a Tribuo class and then iteratively add it to the regexMappingProcessors.put() ?

your guidance with an example / snippet will help.

```
String csv_path = <local file path>;
Map<String, FieldProcessor> regexMappingProcessors = new HashMap<>(); 
reader = new CSVReaderHeaderAware(new FileReader(csv_path));
Map<String, String> record = reader.readMap();
for (Map.Entry<String, String> e : record.entrySet())
	        	regexMappingProcessors.put(e.getKey().toString(), new DoubleFieldProcessor(e.getKey().toString()));
	     				
RowProcessor<ClusterID> rowProcessor = new RowProcessor<>(new EmptyResponseProcessor<>(new ClusteringFactory()), regexMappingProcessors);
CSVDataSource<ClusterID> csvSource = new CSVDataSource<>(Paths.get(csv_path), rowProcessor, false);
Dataset<ClusterID> dataset = new MutableDataset<>(csvSource);
```

Thank you.

**Comment by nsankar** [comment]
@Craigacp  There seems to be a problem when I tried the following 

I created a  method call getHeaders that will read a CSV file and output the list of the  csv headers (features..) . Then I am looping through this list and add it to the regexMappingProcessors as below. 

The trainingHeaderSize list size output is correct. which is 54 (column names / features ) from the attached CSV file. 

But when I check the features from the dataset created using the CSVDataSource as below using dataset.getFeatureMap().size() , it  is showing only 48 instead of 54?

```
List<String> headerItems = test.getHeaders(training_file_path, training_file_name);
		int trainingHeaderSize = headerItems.size();
		System.out.println("trainingHeaderSize: " + trainingHeaderSize);
		for (int h=0; h<trainingHeaderSize; h++) {
			
			String hLabel = headerItems.get(h);
			regexMappingProcessors.put(hLabel, new DoubleFieldProcessor(hLabel));
		}

		
		System.out.println("Loading Training data ........");
   	   	RowProcessor<ClusterID> rowProcessor = new RowProcessor<>(new EmptyResponseProcessor<>(new ClusteringFactory()), regexMappingProcessors);
		CSVDataSource<ClusterID> csvSource = new CSVDataSource<>(Paths.get(csv_path), rowProcessor, false);
		// DATASET from CSV
		Dataset<ClusterID> dataset = new MutableDataset<>(csvSource);
		System.out.println("Train dataset info start........");
		System.out.println("Size:" + " " + dataset.size() );
		System.out.println("Feature space:" + " " + dataset.getFeatureMap().size() ); 
[synthetic_data_prediction_resptime_70_30_derived.csv](https://github.com/oracle/tribuo/files/9308060/synthetic_data_prediction_resptime_70_30_derived.csv)

		System.out.println("Train dataset info end........");
```

**Comment by Craigacp** [comment]
Ah ok. The map named `regexMappingProcessors` is being fed into the `RowProcessor` where it's expecting a map with concrete column names. To use the regex expansion you need to use the constructor mentioned here - https://github.com/oracle/tribuo/issues/251#issuecomment-1185129446, and then you should be able to build a map like this:
```java
Map<String, FieldProcessor> regexMappingProcessors = Collections.singletonMap("*", new DoubleFieldProcessor("*"));
```

Given that's the second issue this month with confusion around the use of regexMappingProcessors we'll bump adding the builder to RowProcessor up the list and make sure it gets in for the next release, which should hopefully make it a bit clearer what's going on.

**Comment by nsankar** [comment]
Got it. Thanks @Craigacp
