### ISSUE TITLE
Limitid extendability by using Enums

### ISSUE THREAD

**Issue by brainbytes42** [oracle/tribuo#284]
Hi there,

I was really happy to find a Java-HDBSCAN-Implementation, but at the same time, I'm a little sad, why there are Enums used for the initialization? DistanceType and NeighboursQueryFactoryType are both enums and therefore not extendable with custom Metrics.
https://github.com/oracle/tribuo/blob/04c6fc35f95ec3843c0e2df3da88b91554c1abc1/Clustering/Hdbscan/src/main/java/org/tribuo/clustering/hdbscan/HdbscanTrainer.java#L197
For my usecase, I have a custom distance-Matric and also a matching custom Datastructure to provide nearest neighbours (it uses the distance between shapes), but I'd need to change the enum and can't just implement a simple interface and inject those custom parts.
Therefore, I think it would be good to migrate those enums to implement an interface that is used for the algorithm; then I could implement the interface and also use my code in the algorithm.

**Comment by Craigacp** [comment]
Wasn't too hard to migrate over to an interface without breaking compatibility, so we'll get this in before 4.3.
