### ISSUE TITLE
Including all the features in a tf-idf transformation of a Tribuo's example

### ISSUE THREAD

**Issue by victor-illuin** [oracle/tribuo#299]
Hello,

I am facing a problem while using Tribuo for a tf-idf transformation use case.

**My use case**

I would like to use Tribuo to create an tf-idf transformer that transforms a phrase into a vector. 

**My problem**

I would like every sentence to be projected into the space represented by the whole set of features (a vector containing a value for each word of my vocabulary for example). For example, if I train my transformer with the sentences "Hello I am John" and "Hello I am William", my set of features (my vocabulary) is : "HELLO", "I", "AM", "JOHN", "WILLIAM". When I transform a dataset containing these two sentences, it works (both sentences yield vectors in the space represented by the whole set of features).

But when I transform an example (even if I densify the example after the transformation), it does not include the features that are not present in the example itself in its representation. For instance, if I transform the example created from the sentence “Hello I am Charles”, the result is a vector in the space composed of the features "HELLO", "I", "AM”, “Charles” but "JOHN" and "WILLIAM” are missing. When I call the isDense method on this densified example, it returns false (and an investigation made me see that this comes from the fact that my example size is smaller than the features size despite the densification that I apply).

I added a code sample below to illustrate this problem and all the facts that I mention above. Please, does anyone see what I am doing wrong there?

Thank you in advance.

Victor

**Code sample**

```
import org.tribuo.Example;
import org.tribuo.MutableDataset;
import org.tribuo.classification.Label;
import org.tribuo.classification.LabelFactory;
import org.tribuo.data.columnar.FieldProcessor;
import org.tribuo.data.columnar.RowProcessor;
import org.tribuo.data.columnar.processors.field.TextFieldProcessor;
import org.tribuo.data.columnar.processors.response.FieldResponseProcessor;
import org.tribuo.data.text.impl.TokenPipeline;
import org.tribuo.datasource.ListDataSource;
import org.tribuo.transform.TransformationMap;
import org.tribuo.transform.TransformerMap;
import org.tribuo.transform.transformations.IDFTransformation;
import org.tribuo.util.tokens.impl.WhitespaceTokenizer;

import java.util.*;
import java.util.stream.Collectors;

public class TribuoTest {
    private static final String ATTRIBUTE_NAME = "PHRASE";

    public static void main(String[] args) {
        // create a row processor to create tribuo examples
        RowProcessor<Label> rowProcessor = createRowProcessor();

        // create data
        List<String> data = Arrays.asList(
                "Hello I am John",
                "Hello I am William"
        );
        List<Example<Label>> dataExamples = createExampleList(rowProcessor, data);
        MutableDataset<Label> dataset = createDataset(dataExamples);

        // create an IDF transformer
        TransformerMap transformer = createTransformer(dataset);

        // dataset tranformation
        MutableDataset<Label> tranformedDataset = transformer.transformDataset(dataset);
        System.out.println(tranformedDataset.getData());
        //[ArrayExample(numFeatures=4,output=HELLO I AM JOHN,weight=1.0,features=[(PHRASE@1-N=Hello, 0.0)(PHRASE@1-N=I, 0.0), (PHRASE@1-N=John, 0.6931471805599453), (PHRASE@1-N=am, 0.0), ]), ArrayExample(numFeatures=4,output=HELLO I AM WILLIAM,weight=1.0,features=[(PHRASE@1-N=Hello, 0.0)(PHRASE@1-N=I, 0.0), (PHRASE@1-N=William, 0.6931471805599453), (PHRASE@1-N=am, 0.0), ])]
        tranformedDataset.densify();
        System.out.println(tranformedDataset.getData());
        //[ArrayExample(numFeatures=5,output=HELLO I AM JOHN,weight=1.0,features=[(PHRASE@1-N=Hello, 0.0)(PHRASE@1-N=I, 0.0), (PHRASE@1-N=John, 0.6931471805599453), (PHRASE@1-N=William, 0.0), (PHRASE@1-N=am, 0.0), ]), ArrayExample(numFeatures=5,output=HELLO I AM WILLIAM,weight=1.0,features=[(PHRASE@1-N=Hello, 0.0)(PHRASE@1-N=I, 0.0), (PHRASE@1-N=John, 0.0), (PHRASE@1-N=William, 0.6931471805599453), (PHRASE@1-N=am, 0.0), ])]
        System.out.println(tranformedDataset.getFeatureMap().keySet());
        //[PHRASE@1-N=John, PHRASE@1-N=am, PHRASE@1-N=Hello, PHRASE@1-N=I, PHRASE@1-N=William]

        // tribuo example tranformation
        String phrase = "Hello I am Charles";
        Example<Label> example = createExample(rowProcessor, phrase);
        Example<Label> transformedExample = transformer.transformExample(example);
        System.out.println(transformedExample);
        //ArrayExample(numFeatures=4,output=HELLO I AM CHARLES,weight=1.0,features=[(PHRASE@1-N=Charles, 1.0)(PHRASE@1-N=Hello, 0.0), (PHRASE@1-N=I, 0.0), (PHRASE@1-N=am, 0.0), ])
        transformedExample.densify(dataset.getFeatureMap());
        System.out.println(transformedExample);
        //ArrayExample(numFeatures=4,output=HELLO I AM CHARLES,weight=1.0,features=[(PHRASE@1-N=Charles, 1.0)(PHRASE@1-N=Hello, 0.0), (PHRASE@1-N=I, 0.0), (PHRASE@1-N=am, 0.0), ])
        System.out.println(transformedExample.isDense(dataset.getFeatureMap()));
        //false
    }

    private static RowProcessor<Label> createRowProcessor() {
        Map<String, FieldProcessor> fieldProcessors = Collections.singletonMap(
                ATTRIBUTE_NAME,
                new TextFieldProcessor(
                        ATTRIBUTE_NAME,
                        new TokenPipeline(new WhitespaceTokenizer(), 1, false)
                )
        );
        return new RowProcessor<>(
                new FieldResponseProcessor<>(
                        ATTRIBUTE_NAME,
                        "",
                        new LabelFactory()
                ),
                fieldProcessors
        );
    }

    private static MutableDataset<Label> createDataset(List<Example<Label>> exampleList) {
        return new MutableDataset<>(
                new ListDataSource<>(exampleList, new LabelFactory(), null)
        );
    }

    private static List<Example<Label>> createExampleList(RowProcessor<Label> rowProcessor, List<String> data) {
        return data.stream().map(d -> createExample(rowProcessor, d)).collect(Collectors.toList());
    }

    private static Example<Label> createExample(RowProcessor<Label> rowProcessor, String data) {
        Optional<Example<Label>> exampleOptional = rowProcessor.generateExample(
                Collections.singletonMap(
                        ATTRIBUTE_NAME,
                        data
                ),
                false);
        if (exampleOptional.isEmpty()) {
            throw new RuntimeException("Tribuo's example generation did not succeed");
        }
        return exampleOptional.get();
    }

    private static TransformerMap createTransformer(MutableDataset<Label> dataset) {
        TransformationMap transformationMap = new TransformationMap(Collections.singletonList(new IDFTransformation()));
        return dataset.createTransformers(transformationMap, true);
    }
}
```

**Comment by Craigacp** [comment]
I think you're hitting a bug/misspecification in how densify works, because we expect that the feature map you supply contains all the features that the example contains, plus all the other features you wish to make dense. However we don't verify that this is true, so the logic gets all confused.

If you make another dataset that contains all three examples, then use the feature map from that for the densify calls, then things behave as expected.

We'll have a think how best to fix this, I'm not sure if modifying the contract for densify so it adds all the features in the example into the list first is better, or if it should throw an exception and have updated documentation explicitly specifying the contract. It may even be both, where `Example.densify(FeatureMap)` adds extra features, and `Example.densify(List<String>)` throws an exception if the example contains features not present in the list.

**Comment by victor-illuin** [comment]
Hello,

Thank you very much for your answer. For information, I’ve juste tried to do what you suggested and it worked.

Regarding the possible ways to fix it that you mentioned, it would be better to add example features in densification in my opinion. 

Another interesting way could be to create another method (or to update the densify one) taking a list of features as argument and that creates an example with the listed features and ignore / remove the ones that are not in this list. In that case you are sure that the example has the same features as the dataset you used to fit the vectoriser (which is a recurrent need according to me when one wants to compare an example to the dataset to measure distances for example).

**Comment by Craigacp** [comment]
I think on reflection we're going to modify densify so that it adds the blank features whatever, though that will require a more complicated rewrite of the internals of the densify methods (and it might be a little slower).

For your use case of measuring distances between examples then I'd recommend using `org.tribuo.math.la.SparseVector.createSparseVector(Example<T>, ImmutableFeatureMap, boolean)` and/or `org.tribuo.math.la.DenseVector.createDenseVector(Example<T>, ImmutableFeatureMap, boolean)` which will build a vector, inserting zeros as appropriate. The `SGDVector` interface exposes several distance calculations (euclidean/l2, manhattan/l1, cosine), and it should be possible to construct more of them by iterating the vectors if we don't have the one you need.

I'm not sure what treatment you want of the features that are present in an example but not in the dataset/feature map, but in Tribuo pretty much all the methods will ignore features not present in the feature map and they won't contribute to the output.
