### ISSUE TITLE
How to get inner model from multi-label classification model?

### ISSUE THREAD

**Issue by marinier** [oracle/tribuo#300]
In following the multi-label classification tutorial, I created an `IndependentMultiLabelTrainer` that wraps a `CARTClassificationTrainer`, which when trained produces an `IndependentMultiLabelModel`. Now I want to get access to the `TreeModel` inside the `IndependentMultiLabelModel` so I can walk it and render it nicely (or even print it using the built-in `toString()`). But there doesn't seem to be a getter for the models. How can I access these models?

Note this is also an issue for other similar classes, like `ClassifierChainModel`.

**Is your question about a specific Tribuo class?**

`IndependentMultiLabelModel`
`ClassifierChainModel`

**System details**
- 4.3.0
- Java 17
- Windows 10

**Comment by Craigacp** [comment]
We'll add the accessors to those models. For the time being you could save them out as protobufs and pull out the individual model protos then deserialize them to models, though that is ugly, slow and bad for memory usage.

**Comment by marinier** [comment]
Currently I'm just prototyping, so performance isn't an issue. That said, I am apparently not familiar enough with protobuf to figure out how to deserialize the `models` field out of the serialized model. I'm trying to do something like this:

```java
IndependentMultiLabelModel model = (IndependentMultiLabelModel) trainer.train(dataset);
var serializedModel = model.serialize();
var fieldDescriptor = serializedModel.getDescriptorForType().findFieldByName("serialized_data");
var any =  (Any) serializedModel.getField(fieldDescriptor);
```

But I'm getting hung up on this `Any` field -- I don't know how to get the down to the actual `models` field. Can you give me a hint on how to proceed?

**Comment by Craigacp** [comment]
It's unfortunately a little involved as protobuf doesn't have polymorphism but we need it to represent model subtypes. So you should unpack the `Any` into a `IndependentMultiLabelModelProto` - https://github.com/oracle/tribuo/blob/main/MultiLabel/Core/src/main/java/org/tribuo/multilabel/baseline/IndependentMultiLabelModel.java#L103, and then you can iterate the models deserializing them as you go, like this for loop does - https://github.com/oracle/tribuo/blob/main/MultiLabel/Core/src/main/java/org/tribuo/multilabel/baseline/IndependentMultiLabelModel.java#L128.

**Comment by Craigacp** [comment]
But I'd like to say that unpicking the protobufs like this is not supported, as we reserve the right to mess about with the internals of them. It'll work until we get the accessors in though, which will probably come in a `4.3.1` in the near-ish future.

**Comment by marinier** [comment]
That worked, thanks! Looking forward to 4.3.1 :)
