### ISSUE TITLE
Document how to load Multi-Label Classification data from CSV

### ISSUE THREAD

**Issue by marinier** [oracle/tribuo#301]
**Is your feature request related to a problem? Please describe.**

I was trying to follow the Multi-Label Classification tutorial, but my data is in CSV files. It took a while to figure out (by tracing through the code) that unlike with single-label classification, the labels are each expected to be in a separate column with the strings true/false to indicate if each row has that output label. Based on how single-label classification works, I was expecting to have multiple label columns (e.g., label 1, label 2, etc.) with one label in each column (blanks allowed if the example has fewer labels than the max allowed).

**Describe the solution you'd like**

Now that I understand how CSV data needs to be formatted I have no issue with it. What I'd like is better documentation on what the `CSVLoader` is expecting the data to look like. This would ideally go in the javadocs, but a tutorial on how to structure data would be nice, too.

**Describe alternatives you've considered**

Tracing through the code worked (I was able to figure it out) but was painful.

**Comment by Craigacp** [comment]
Sure we can improve the docs there. The preferred method for working with more complex CSV data is to use `CSVDataSource` and the `RowProcessor` machinery, but that's also not obvious for multilabel data so needs better documentation (you can see how it should work by looking at the code for `CSVLoader` as `CSVLoader` constructs a `RowProcessor` under the covers).

**Comment by marinier** [comment]
Yeah, that's what I basically ended up doing. What made it extra confusing is that `CSVLoader` has some constructors with an argument called `responseName`, which is used in the single-label case to indicate the name of a column that contains the labels (e.g., a bunch of strings), but for the multi-label case the argument is called `responseNames`, but indicates columns whose names are the labels, and whose contents are strings that can be mapped to booleans. These two different usages of `responseName` really threw me for a loop. The javadoc for each is even the same. I think if the javadoc for each were updated to explain what was expected of those columns, it would be much clearer.

**Comment by Craigacp** [comment]
Ok, we'll definitely fix that. Modifying the javadoc is easy, writing fresh tutorials requires more thought.

**Comment by Craigacp** [comment]
Part of the problem is that `MultiLabelFactory` doesn't let the user select the split character (unlike `RegressionFactory`) and it defaults to `,` so you can't present a delimited list of labels in a single column of a csv file without juggling. I think the longer term solution is to fix that issue in `MultiLabelFactory`, then revise `CSVLoader` and the response processors to better handle multi-output things. We'd done a pass of this before the initial v4 release (which is how `RegressionFactory` got fixed), but it could do with another one.

**Comment by Craigacp** [comment]
The PR adds a test for the quoting behaviour and improves the documentation. Changing `MultiLabelFactory` will involve changing the serialized representation and so that needs a little more thought. We'll put it on the todo list for v5, but that's unlikely to be backported to a v4.3.x release.
