### ISSUE TITLE
Negative values for term counts when using feature hashing

### ISSUE THREAD

**Issue by christianwaldmann** [oracle/tribuo#307]
For a text classification task, I'm using feature hashing in a `TokenPipeline` to map the features (uni and bigrams) down to a smaller space. Then I want to apply a IDF transformation to them.
However this causes the following Exception:
````
java.lang.IllegalArgumentException: Example contained a NaN feature
````
How can I fix this?

I'm using the TokenPipeline like this: `var pipeline = new TokenPipeline(new UniversalTokenizer(), 2, true, maxNrFeatures)`.
When inspecting the values (term counts) for the features after extraction, I can see that some of them have negative values for some reason. I assume this causes the NaN values after applying the `IDFTransformation` to them.
Why are there negative values for term counts after using feature hashing?

**Is your question about a specific Tribuo class?**
`TokenPipeline`

**System details**
- Tribuo version 4.3.0

**Comment by Craigacp** [comment]
Long ago for reasons that are not documented we made the `FeatureHasher` generate the feature value from the hash as well. That interacts very poorly with term counting, so we'll add an option to control that. The default term counting pipeline will ensure that the hasher emits unit valued features.
