### ISSUE TITLE
Tribuo 4.3.0 set up / Build failure issue (java: cannot find symbol   symbol:   class Tribuo)

### ISSUE THREAD

**Issue by nsankar** [oracle/tribuo#314]
**Issue**

I set up a IntelliJ Idea project using Tribuo git url and then selected (checked out) the 4.3.X release branch using the IntelliJ git menu checkout. The project got set up . When I build the project, I get the following build failed error .  Kindly suggest how to resolve this.

C:\Users\Lenovo\tribuo\tribuo\Core\src\main\java\org\tribuo\provenance\EvaluationProvenance.java:23:18
java: cannot find symbol
  symbol:   class Tribuo
  location: package org.tribuo

**- Java version - JDK 17 
- Windows 10**

**Additional context**
**Below is the IntelliJ screenshots of the issue. (when the Build failed)**

![image](https://user-images.githubusercontent.com/431890/209784228-41ca815d-1069-404f-8dec-e2b09607e745.png)

![image](https://user-images.githubusercontent.com/431890/209784658-14f36d96-64e8-4155-ba42-dc814e7ee5fe.png)

**Comment by Craigacp** [comment]
Run a build in Maven at the command line (or explicitly run the compile target in Maven from intellij). For some reason intellij doesn't always run the pre-build hook we use to generate the Tribuo class containing the version information.

**Comment by nsankar** [comment]
@Craigacp Is the following linear scaling transformation API taken from the tutorial still valid in 4.3.X release?

`TransformationMap transformations = new TransformationMap(List.of(new LinearScalingTransformation(0,1))); 
		TransformerMap map = dataset.createTransformers(transformations);`
		
I get the following error as below . If it is not supported, please let me know how to create a linear scaled model (0 to 1 min-max). Thank in advance

![image](https://user-images.githubusercontent.com/431890/209836230-fd036b79-d2a2-4008-8713-5ef17cd39d63.png)

**Comment by Craigacp** [comment]
The `List.of` method is in Java 9 or higher, and the tutorials are written in Java 10 or higher. Tribuo itself works with Java 8, and if your project also requires Java 8 then you'll need to modify the tutorial code to work. I'd recommend using a newer version of Java than Java 8 though, and Tribuo v5 will require Java 17 when it comes out.
