### ISSUE TITLE
getClusters in HDBSCAN transformed model

### ISSUE THREAD

**Issue by nsankar** [oracle/tribuo#316]
**The question is how to get the cluster information from a transformed model in HDBSCAN ?**

I have a transformed hdbscan model (linear transformation)

` TransformTrainer transformed = new TransformTrainer(HDBSCANTrainer,transformations);
TransformedModel transformedModel = (TransformedModel) transformed.train(dataset);`

The transformedModel does not have a method to get clusters (getclusters).
I tried using getInnerModel as a normal HDBSCAN model as below. But the output is a empty list.
`HdbscanModel hdbscanInner = (HdbscanModel) transformedModel.getInnerModel();
System.out.println(hdbscanInner.getClusters().size());
`

Wondering how to getClusters() from the transformed model . Kindy suggest.

**Comment by Craigacp** [comment]
`((HdbscanModel) transformedModel.getInnerModel()).getClusters()` is the correct way to access the clusters. Maybe the HDBSCAN run assigned everything to noise?

**Comment by nsankar** [comment]
ok. will check that
