### ISSUE TITLE
Import CARTClassificationTrainer without using tribuo-all

### ISSUE THREAD

**Issue by christianwaldmann** [oracle/tribuo#317]
I use maven for dependency management and want to use a `CARTClassificationTrainer`. When I import all of Tribuo with `tribuo-all`, I can import it like this: `import org.tribuo.classification.dtree.CARTClassificationTrainer;`. Now I want to switch from importing all of Tribuo to just the parts I need.

I would expect that it should be enough to import the relevant parts like this:
````
<dependency>
  <groupId>org.tribuo</groupId>
  <artifactId>tribuo-classification-tree</artifactId>
  <version>4.3.0</version>
  <type>pom</type>
</dependency>
````
However this results in the error message: `The import org.tribuo.classification.dtree cannot be resolved`.

Why doesn't this work?

My current fix is to use `tribuo-classification-experiments` instead. This is suboptimal because in the documentation it's stated that experiments shouldn't be imported into projects as it's purely intended for development or testing.

**Is your question about a specific Tribuo class?**
`CARTClassificationTrainer`

**System details**
- Tribuo version 4.3.0

**Comment by Craigacp** [comment]
I think you want to remove the `<type>pom</type>` from the dependency, because that doesn't actually pull in the code, just the dependencies of the code.

**Comment by christianwaldmann** [comment]
That fixed it, thanks!
