### ISSUE TITLE
mRMR

### ISSUE THREAD

**Issue by Mohammed-Ryiad-Eiadeh** [oracle/tribuo#327]
Dear Adam,

I am currently under a process of making a research for image classification. Image features were extracted by Orange tool using Inception V3 NN, and I used mRMR, Bagging, and FM classifier from Tribuo library. Now, I would like to explain mRMR FS algorithm in details and I am wondering about the functions you used to construct this filter. Moreover, I prefere to know the study you relaied on to build this algorithm and it would be great to know that from you and it would be awsoum if you give me the title of the study.

Regards,
Mohammad.

**Comment by Craigacp** [comment]
The mRMR implementation in Tribuo implements the mRMR algorithm from "H. Peng, F. Long, and C. Ding. Feature Selection Based on Mutual Information: Criteria of Max-Dependency, Max-Relevance, and Min-Redundancy. IEEE Transactions on Pattern Analysis and Machine Intelligence, 27(8):1226–1238, 2005". The approach is discussed in detail in Brown et al 2012 (https://www.jmlr.org/papers/volume13/brown12a/brown12a.pdf) which I was a co-author on, and was implemented in the [FEAST library](https://github.com/Craigacp/FEAST).

**Comment by Mohammed-Ryiad-Eiadeh** [comment]
I am sorry, I referred to the mRMR implementation and I noticed that you put the reference for the study. Thank you so much.
