### ISSUE TITLE
Docs recommending IJava

### ISSUE THREAD

**Issue by Camilotk** [oracle/tribuo#332]
The Docs, in the "Tutorial" part recommend the use of IJava to run Java Kernels on Jupyter Notebooks:
![image](https://user-images.githubusercontent.com/30880723/230796699-e1b5f411-a869-4847-bf41-b3f6436d41cf.png)

The last commit in the IJava repository was more than 2y. ago.

There are even [issues asking if the project is currently maintained](https://github.com/SpencerPark/IJava/issues/125) without any answer from  more than a year ago.

There's any alternative? Shouldn't it have a fork from the Community since there's a lot of PR's and none of them are being merged?

**Comment by Craigacp** [comment]
I've not come across a well maintained Java Jupyter kernel, though as you say there are many forks of the IJava kernel. For internal uses & demos it's fine, and we continue to use it. There was a demo of JavaFX notebooks during the JavaFX talk at JavaOne, but unfortunately that's not available yet (and I'm not sure it's a direct replacement for the things we use Jupyter for).

Unfortunately we don't have the bandwidth to fork and maintain IJava ourselves. The DJL team have their own fork (https://github.com/frankfliu/IJava) which should be a drop in replacement, but they aren't tagging releases so it's hard to point users at.

**Comment by Camilotk** [comment]
Thanks! The most forks I've seen was from issues in original project, but not checked how well maintained and up to point they are.

Will close the issue because seen as made the point and is something well know and everyone is aware at.

I'm really grateful for the answer and your time doing it.

**Comment by andrus** [comment]
I know it's been resolved, but wanted to mention that the iJava kernel lives on as JJava, which is a fork that we are planning to support going forward under the DFLib project:

* https://github.com/SpencerPark/IJava/issues/161 
* https://github.com/dflib/jjava
