### ISSUE TITLE
Training loss

### ISSUE THREAD

**Issue by Mohammed-Ryiad-Eiadeh** [oracle/tribuo#353]
I am working in a regression task and I know how to use XChart library for plotting some useful stuff for demonstration purposes, my question is how to fetch the training loss value in each iteration to plot it and I mean that it is good if I can store thses values in a list or in an array?!

**Comment by Craigacp** [comment]
The only way to get that information out at the moment is to process the logging output after the fact to read the printed loss values.

The training interface that Tribuo provides doesn't support passing out extra information from the model training run aside from the model itself, we'd have to design some kind of callback mechanism. We are looking at improving the termination criteria of the SGD based models, so it might be possible to fold something into that.
