### ISSUE TITLE
Weight and Bias in NN

### ISSUE THREAD

**Issue by Mohammed-Ryiad-Eiadeh** [oracle/tribuo#354]
Is there any method in Tribuo engin where we can get the weight and bias values after training the model?

**Comment by Craigacp** [comment]
For the linear SGD based models - https://tribuo.org/learn/4.3/javadoc/org/tribuo/common/sgd/AbstractLinearSGDModel.html#getWeightsCopy(), for the factorisation machines - https://tribuo.org/learn/4.3/javadoc/org/tribuo/common/sgd/AbstractFMModel.html and similar methods on `AbstractFMModel`.

**Comment by Mohammed-Ryiad-Eiadeh** [comment]
The model is based on graph DefTuple and TensorFlow

**Comment by Craigacp** [comment]
We don't expose methods to access the weights of TF models. If you save it out as a TF Checkpoint then you can load it in using regular TF-Java methods and fetch the variables out like that. Tribuo's protobuf representation also stores them in a more accessible format but you'd need to read the protobuf yourself.
