### ISSUE TITLE
SQLDataSource Example

### ISSUE THREAD

**Issue by lazydog2** [oracle/tribuo#366]
**Ask the question**
I'm trying to use an SQLDataSource for HDBSCAN clustering and would appreciate an example of using SQLDataSource as there doesn't seem to be one in the documentation.

**Is your question about a specific ML algorithm or approach?**
HDBSCAN

**Is your question about a specific Tribuo class?**
SQLDataSource

**System details**
- Tribuo version: 4.3.1
- Java version: 11
- OS/Architecture: Ubuntu

**Additional context**
N/A

**Comment by Craigacp** [comment]
Aside from the SQL connection information `SQLDataSource` behaves exactly like `CSVDataSource` in terms of how Tribuo processes the data, which you can see in the [columnar data tutorial](https://tribuo.org/learn/4.3/tutorials/columnar-tribuo-v4.html). Is there something about how the SQL connection works that we should document better? I think internally we may only have used it against Oracle DBs, but it should talk to anything that works via JDBC.

**Comment by Craigacp** [comment]
Yes, you should use a `ClusteringFactory` for HDBSCAN. The `SQLDataSource` should probably be refactored to pull its output factory from the `RowProcessor`, which is how the `CSVDataSource` works. We must have missed that in the refactor which unified the columnar processing infrastructure.

If you have a ground truth clustering that you want to load in for later comparison then you'll need to write a `ResponseProcessor` which creates the appropriate `ClusterID` object from your source. Otherwise use `EmptyResponseProcessor` and pass it a `ClusteringFactory`.

**Comment by Craigacp** [comment]
Yes, that's the one.

All Tribuo feature values are doubles, you can use RowProcessor to transform other things into features but the values must be doubles as that's what all the computational backends support.

**Comment by Craigacp** [comment]
Yes, those both work for unsupervised anomaly detection assuming by "unsupervised" you mean you only have a sample of non-anomalous data.

**Comment by Craigacp** [comment]
Unfortunately both LibSVM and LibLinear do anomaly detection by computing the probability of the incoming point being generated by their model of the training data, so if there are any anomalies in the training data then they make the incoming data more likely to be considered normal.

**Comment by Craigacp** [comment]
It means that it's not required for the core infrastructure of the anomaly detection packages (e.g. all the stuff in `tribuo-anomaly-core`) but it is required in the two algorithms that we have implemented for anomaly detection (LibSVM and LibLinear). Tribuo's development is mostly driven by the use cases we've had, and for anomaly detection the requirement that the training data not be anomalous has been acceptable so we haven't had to implement other algorithms which can deal with the training data being a mixture of anomalous and normal data.
