### ISSUE TITLE
SQLDataSource does not close connections

### ISSUE THREAD

**Issue by Artraxon** [oracle/tribuo#375]
The SQLDataSource does not close connections and leaks them.
This goes well if it is invocated at a low frequency and the jdbc driver releases connections on finalize(). 
But, this is not always the case and will lead to the database either dropping connections or crashing. Either way, its not the proper way to handle JDBC resources.

The culprit is the getStatement() method in SQLDBConfig, which creates a statement but discards the connection.
Its only used in SQLDataSource.rowIterator(). The SQLDataSource should retrieve the connection and at least store it in the SQLDataSource.

SQLDataSource already implements AutoCloseable, so the connections can be closed at the end of close().

**Comment by Craigacp** [comment]
Thanks for the report, we've pushed a fix. We'd not noticed this as the data source only tends to be iterated once when it's loaded into a dataset and a single leaked connection wasn't enough to cause us any problems.
