### ISSUE TITLE
Dataset from array

### ISSUE THREAD

**Issue by tom-whitehead** [oracle/tribuo#379]
Hey guys, I'm trying to use your HDBSCAN implementation to do some clustering. Apologies if this question is a little basic, but I can't figure out how to create a `MutableDataSet` to train the model on from my embeddings, which are of type `double[][]`. I have the matrix of doubles as a consequence of upstream processing (dimensionality reduction). 

the only way I can figure out how to do it is write the array to a csv file then read it to `CSVDataSource`, but that doesn't make much sense. 

Many thanks in advance

**Comment by Craigacp** [comment]
You can use [`ListDataSource`](https://tribuo.org/learn/4.3/javadoc/org/tribuo/datasource/ListDataSource.html) to make a dataset from a list of [`ArrayExample<ClusterID>`](https://tribuo.org/learn/4.3/javadoc/org/tribuo/impl/ArrayExample.html). You can use [`SimpleDataSourceProvenance`](https://tribuo.org/learn/4.3/javadoc/org/tribuo/provenance/SimpleDataSourceProvenance.html) to make the provenance, and you'll need a [`ClusteringFactory`](https://tribuo.org/learn/4.3/javadoc/org/tribuo/clustering/ClusteringFactory.html) in various places.

**Comment by tom-whitehead** [comment]
@Craigacp Thanks very much! I got it working
