### ISSUE TITLE
Tests failing due to a locale issue

### ISSUE THREAD

**Issue by StijnSimons** [oracle/tribuo#39]
**Describe the bug**
While executing `mvn clean install`, one of the tests ([LabelEvaluatorTest](https://github.com/oracle/tribuo/blob/215c6877352da572dd4d96e943d53e046a872147/Classification/Core/src/test/java/org/tribuo/classification/evaluation/LabelEvaluatorTest.java#L222)) will fail due to an issue with locales using a comma instead of a point in numbers with a decimal point.  

**To Reproduce**
Set your PC's locale to any language using a comma (,) instead of a point (.). In my case this was Belgian (Dutch).

**Expected behaviour**
The tests should still pass on computers using a different locale.

**Screenshots**
![image](https://user-images.githubusercontent.com/17461028/93718805-b2a79680-fb7e-11ea-8fa3-b2592e75b468.png)

**System information:**

 - OS: macOS
 - Java Version: Java 15 (build 15+36-1562)
 - JDK Vendor: OpenJDK

**Comment by Craigacp** [comment]
I've opened a PR which should fix this issue. Telling Maven to use nl_BE.UTF-8 triggered the failure on my machine, and the PR fixes it. The rest of the tests already pass in that locale.

**Comment by Craigacp** [comment]
Closing this as the patch has been integrated. Feel free to re-open it if this locale issue recurs, or make a new issue if there are other localisation issues.
