### ISSUE TITLE
MNIST is not loading in Config.json

### ISSUE THREAD

**Issue by nikkisingh111333** [oracle/tribuo#58]
i m using tribuo and trying to find mnist dataset in config json ...all the components are loading nut MNIST test/train is giving me NULL POINTER EXCEPTION. 
1.my config code
` ConfigurationManager.addFileFormatFactory(new JsonConfigFactory());
   String configFile = "config.json"; 
   ConfigurationManager cm = new ConfigurationManager(configFile);
   System.out.println( cm.lookup("mnist-train"));
    //GIVING NULL POINTER EXCEPTION
     System.out.println( cm.lookup("logistic")); //RUNNING PERFECTLY FINE RETURNING LOGISSTIC TRAINER `
2.MY CONFIG.JSON 
![Screenshot (37)](https://user-images.githubusercontent.com/49682940/95676540-63341380-0bdc-11eb-87a3-309df0c71c3a.png)
 whats the matter?

**Comment by neomatrix369** [comment]
I got a similar one in the Configuration Tutorial, see attached HTML file, has multiple errors including one for MNist:
```
com.oracle.labs.mlrg.olcut.config.PropertyException: Component: mnist-train, RuntimeException thrown by postConfig (caused by null)
	at com.oracle.labs.mlrg.olcut.config.PropertySheet.getOwner(PropertySheet.java:332)
	at com.oracle.labs.mlrg.olcut.config.PropertySheet.getOwner(PropertySheet.java:239)
	at com.oracle.labs.mlrg.olcut.config.ConfigurationManager.innerLookup(ConfigurationManager.java:1374)
	at com.oracle.labs.mlrg.olcut.config.ConfigurationManager.lookup(ConfigurationManager.java:1357)
	at com.oracle.labs.mlrg.olcut.config.ConfigurationManager.lookup(ConfigurationManager.java:1300)
	at .(#37:1)
```
 
[configuration-tribuo-v4-notebook-errors.html.txt](https://github.com/oracle/tribuo/files/5361125/configuration-tribuo-v4-notebook-errors.html.txt)
_(drop .txt in the name of attached file)_

**Comment by Craigacp** [comment]
No I think that's the same one. I get this stack trace out if the file it's trying to load don't exist:
```
Property Exception component:'train' - RuntimeException thrown by postConfig (caused by null)
com.oracle.labs.mlrg.olcut.config.PropertyException: Component: train, RuntimeException thrown by postConfig (caused by null)

	at com.oracle.labs.mlrg.olcut.config.PropertySheet.getOwner(PropertySheet.java:332)
	at com.oracle.labs.mlrg.olcut.config.PropertySheet.getOwner(PropertySheet.java:239)
	at com.oracle.labs.mlrg.olcut.config.ConfigurationManager.innerLookup(ConfigurationManager.java:1374)
	at com.oracle.labs.mlrg.olcut.config.ConfigurationManager.lookup(ConfigurationManager.java:1357)
	at com.oracle.labs.mlrg.olcut.config.ConfigurationManager.lookup(ConfigurationManager.java:1300)
Caused by: java.lang.NullPointerException
	at java.base/java.io.DataInputStream.readShort(DataInputStream.java:316)
	at org.tribuo.datasource.IDXDataSource.readData(IDXDataSource.java:261)
	at org.tribuo.datasource.IDXDataSource.read(IDXDataSource.java:173)
	at org.tribuo.datasource.IDXDataSource.postConfig(IDXDataSource.java:142)
	at com.oracle.labs.mlrg.olcut.config.PropertySheet.getOwner(PropertySheet.java:326)
	... 68 more
```

I'd expected it to throw a `FileNotFoundException` there, but due to the way it's opening the stream it gets a null back. I'll fix it to throw `FileNotFoundException`. If you've got a different "caused by" section then post back on this issue as it might be something else.

The data files needed for the configuration tutorial are listed at the top of it, you need all 4 files (http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz, http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz, http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz, http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz). If you've got the files in the root of the tutorials directory, and you're still getting the issue then I'll need the rest of the stack trace.

**Comment by Craigacp** [comment]
However running the configuration tutorial on Windows will lead to issues with XGBoost as the XGBoost binary that the developers put on Maven central doesn't have a Windows dll in it, only macOS and Linux. It's possible to compile XGBoost 1.0.0 (which Tribuo 4.0 uses) for Windows (I've done this for internal use and contributed fixes for it upstream) and then adding that dll to the XGBoost jar next to the so and dylib will make it work.

**Comment by Craigacp** [comment]
The linked PR has a fix and a unit test for the fix using both the config system and the constructor.

**Comment by neomatrix369** [comment]
> However running the configuration tutorial on Windows will lead to issues with XGBoost as the XGBoost binary that the developers put on Maven central doesn't have a Windows dll in it, only macOS and Linux. It's possible to compile XGBoost 1.0.0 (which Tribuo 4.0 uses) for Windows (I've done this for internal use and contributed fixes for it upstream) and then adding that dll to the XGBoost jar next to the so and dylib will make it work.

_So far only running on Linux (inside clean docker container - I hope it's clean)_ so won't be an issue till someone ports my work into Windows. It should work on the MacOS out of the box from past experience.

**Comment by Craigacp** [comment]
> > However running the configuration tutorial on Windows will lead to issues with XGBoost as the XGBoost binary that the developers put on Maven central doesn't have a Windows dll in it, only macOS and Linux. It's possible to compile XGBoost 1.0.0 (which Tribuo 4.0 uses) for Windows (I've done this for internal use and contributed fixes for it upstream) and then adding that dll to the XGBoost jar next to the so and dylib will make it work.
> 
> _So far only running on Linux (inside clean docker container - I hope it's clean)_ so won't be an issue till someone ports my work into Windows. It should work on the MacOS out of the box from past experience.

Yeah, my dev environment is macOS so it works there. The only other thing to note is that macOS needs `libomp` installed (as will the newer versions of onnx-runtime when we upgrade to that), which is noted in the `doc-fixes` branch, I missed it in the docs pass for the initial release.
