### ISSUE TITLE
Tutorial: evaluation of the XGBoost ensemble training fails

### ISSUE THREAD

**Issue by neomatrix369** [oracle/tribuo#59]
**Describe the bug**

Running the below cell in the [Regression tutorial](https://github.com/oracle/tribuo/blob/main/tutorials/regression-tribuo-v4.ipynb) fails:

```java
var xgbModel = train("XGBoost",xgb,trainData);
evaluate(xgbModel,evalData);
```
with these results:

```java
---------------------------------------------------------------------------
java.lang.NoClassDefFoundError: Could not initialize class ml.dmlc.xgboost4j.java.XGBoostJNI
	at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:109)
	at org.tribuo.common.xgboost.XGBoostTrainer.convertExamples(XGBoostTrainer.java:309)
	at org.tribuo.regression.xgboost.XGBoostRegressionTrainer.train(XGBoostRegressionTrainer.java:174)
	at org.tribuo.regression.xgboost.XGBoostRegressionTrainer.train(XGBoostRegressionTrainer.java:64)
	at org.tribuo.Trainer.train(Trainer.java:44)
	at .train(#45:4)
	at .do_it$Aux(#57:1)
	at .(#57:1)

```

**To Reproduce**

Run notebook in a docker container using these steps at https://github.com/neomatrix369/awesome-ai-ml-dl/tree/master/examples/tribuo:

```
git clone https://github.com/neomatrix369/awesome-ai-ml-dl/tree/master/
cd awesome-ai-ml-dl/examples/tribuo
./docker-runner.sh --notebookMode --runContainer

### wait it downloads the contain and browser opens up
### or open the browser to http://localhost:8888/notebooks/tribuo/tutorials/regression-tribuo-v4.ipynb
```

**Expected behaviour**

Should have shown these results:

```
Training XGBoost took (00:00:00:375)
Evaluation (train):
  RMSE 0.143871
  MAE 0.097167
  R^2 0.968252
Evaluation (test):
  RMSE 0.599478
  MAE 0.426673
  R^2 0.447378
```

**Screenshots**

![Screen Shot 2020-10-11 at 14 00 22](https://user-images.githubusercontent.com/1570917/95679388-67573580-0bca-11eb-9ed5-54d6d392d7b1.png)

**System information:**

 - OS: Linux 6a5b46663314 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Java Version: 11
 - JDK Vendor: 
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-jvmci-19.3-b05-LTS)
OpenJDK 64-Bit GraalVM CE 19.3.0 (build 11.0.5+10-jvmci-19.3-b05-LTS, mixed mode, sharing)

** Jar versions **
```
tribuo-classification-experiments-4.0.0-jar-with-dependencies.jar
tribuo-core-4.0.0.jar
tribuo-json-4.0.0-jar-with-dependencies.jar
tribuo-regression-sgd-4.0.0-jar-with-dependencies.jar
tribuo-regression-tree-4.0.0-jar-with-dependencies.jar
tribuo-regression-xgboost-4.0.0-jar-with-dependencies.jar
```

**Comment by Craigacp** [comment]
I can't figure out the base image you're using, is it this - https://hub.docker.com/layers/valohai/jupyhai/latest/images/sha256-0ae21dee7e887c17eec73f5b04533ba48bdba896e46838d4aecf9264d52862d9?context=explore ?

Either way, we've have some dependency issues when using XGBoost in containers (see the note at the bottom of here - https://tribuo.org/learn/4.0/javadoc/org/tribuo/common/xgboost/XGBoostTrainer.html).

The libraries it expects according to ldd are:
```	linux-vdso.so.1 (0x00007ffffcff7000)
	libjvm.so => not found
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f1a5f1ba000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1a5f197000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1a5f18c000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1a5efab000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1a5ee5c000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1a5ee3f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1a5ec4d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1a5f860000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1a5ec47000)```

It'll pull in libjvm automatically as it's already in the process space when you load it via JNI, so I suspect it's either libc, libstdc++ or libgomp you're missing.

**Comment by neomatrix369** [comment]
> I can't figure out the base image you're using, is it this - https://hub.docker.com/layers/valohai/jupyhai/latest/images/sha256-0ae21dee7e887c17eec73f5b04533ba48bdba896e46838d4aecf9264d52862d9?context=explore ?
> 

I'm planning to move to a simple base image, I;m only using this as it was quick for me to come up with a working notebook in a container. Just to get things to work first.

> Either way, we've have some dependency issues when using XGBoost in containers (see the note at the bottom of here - https://tribuo.org/learn/4.0/javadoc/org/tribuo/common/xgboost/XGBoostTrainer.html).
> 
> The libraries it expects according to ldd are:
> 
> ```
> 	libjvm.so => not found
> 	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f1a5f1ba000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1a5f197000)
> 	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1a5f18c000)
> 	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1a5efab000)
> 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1a5ee5c000)
> 	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1a5ee3f000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1a5ec4d000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f1a5f860000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1a5ec47000)
> ```
> 
> It'll pull in libjvm automatically as it's already in the process space when you load it via JNI, so I suspect it's either libc, libstdc++ or libgomp you're missing.

I will look closely into this, I might need to install these correctly in the container. Thanks for the heads up, now I see why the XGBoost tests are also failing.

**Comment by neomatrix369** [comment]
So far I have a working Classification example inside the Jupyter (IJava) notebook, so it's first accomplishment - that tutorial requires minimum dependencies I think.

**Comment by Craigacp** [comment]
Yeah, the classification, clustering and anomaly detection tutorials are pure Java, so should run anywhere you've got Java 10+ up (for the `var` keyword). The regression and configuration tutorials use XGBoost4J which loads in the XGBoost native library, and so you could hit dependency issues.

**Comment by neomatrix369** [comment]
> Yeah, the classification, clustering and anomaly detection tutorials are pure Java, so should run anywhere you've got Java 10+ up (for the `var` keyword). The regression and configuration tutorials use XGBoost4J which loads in the XGBoost native library, and so you could hit dependency issues.

Got it, I'm patching my build image so these issues should reduce or go away for good. For now, I need on working example to know the docker image is fine to work with and build further.

**Comment by neomatrix369** [comment]
> Yeah, the classification, clustering and anomaly detection tutorials are pure Java, so should run anywhere you've got Java 10+ up (for the `var` keyword). The regression and configuration tutorials use XGBoost4J which loads in the XGBoost native library, and so you could hit dependency issues.

You suggestions worked @Craigacp, see
```
[INFO] Reactor Summary for Tribuo 4.1.0-SNAPSHOT:
[INFO]
[INFO] Tribuo ............................................. SUCCESS [ 17.524 s]
[INFO] Core ............................................... SUCCESS [01:55 min]
[INFO] tribuo-util ........................................ SUCCESS [  0.051 s]
[INFO] Tokenization ....................................... SUCCESS [  6.450 s]
[INFO] Data ............................................... SUCCESS [ 25.787 s]
[INFO] Json ............................................... SUCCESS [01:43 min]
[INFO] Math ............................................... SUCCESS [  8.937 s]
[INFO] tribuo-interop ..................................... SUCCESS [  0.043 s]
[INFO] Interop-Core ....................................... SUCCESS [  1.315 s]
[INFO] tribuo-common ...................................... SUCCESS [  0.058 s]
[INFO] Common-Tree ........................................ SUCCESS [  1.902 s]
[INFO] tribuo-classification .............................. SUCCESS [  0.072 s]
[INFO] Classification-Core ................................ SUCCESS [  7.346 s]
[INFO] tribuo-regression .................................. SUCCESS [  0.076 s]
[INFO] Regression-Core .................................... SUCCESS [  4.109 s]
[INFO] Interop-ONNX ....................................... SUCCESS [01:21 min]
[INFO] Interop-Tensorflow ................................. SUCCESS [ 11.693 s]
[INFO] Common-LibLinear ................................... SUCCESS [  1.360 s]
[INFO] Common-LibSVM ...................................... SUCCESS [  0.957 s]
[INFO] Common-NearestNeighbour ............................ SUCCESS [  1.634 s]
[INFO] Common-XGBoost ..................................... SUCCESS [  9.747 s]
[INFO] tribuo-anomaly ..................................... SUCCESS [  0.031 s]
[INFO] AnomalyDetection-Core .............................. SUCCESS [  1.774 s]
[INFO] AnomalyDetection-LibSVM ............................ SUCCESS [ 13.182 s]
[INFO] Classification-MultinomialNaiveBayes ............... SUCCESS [  5.849 s]
[INFO] Classification-Tree ................................ SUCCESS [  6.487 s]
[INFO] Classification-LibLinear ........................... SUCCESS [  7.553 s]
[INFO] Classification-LibSVM .............................. SUCCESS [  6.830 s]
[INFO] Classification-SGD ................................. SUCCESS [  7.014 s]
[INFO] Classification-XGBoost ............................. SUCCESS [ 31.476 s]
[INFO] Classification-Experiments ......................... SUCCESS [  8.563 s]
[INFO] Regression-SLM ..................................... SUCCESS [  9.759 s]
[INFO] Regression-Tree .................................... SUCCESS [  7.357 s]
[INFO] Classification-Explanations ........................ SUCCESS [ 17.887 s]
[INFO] InformationTheory .................................. SUCCESS [  2.038 s]
[INFO] tribuo-clustering .................................. SUCCESS [  0.049 s]
[INFO] Clustering-Core .................................... SUCCESS [  1.617 s]
[INFO] Clustering-KMeans .................................. SUCCESS [  7.630 s]
[INFO] tribuo-multilabel .................................. SUCCESS [  0.021 s]
[INFO] MultiLabel-Core .................................... SUCCESS [  1.941 s]
[INFO] Regression-LibLinear ............................... SUCCESS [  5.967 s]
[INFO] Regression-LibSVM .................................. SUCCESS [  6.154 s]
[INFO] Regression-SGD ..................................... SUCCESS [  6.659 s]
[INFO] Regression-XGBoost ................................. SUCCESS [ 15.330 s]
[INFO] tribuo-all ......................................... SUCCESS [  0.023 s]
[INFO] tribuo-tests ....................................... SUCCESS [  0.901 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:34 min
[INFO] Finished at: 2020-10-11T16:01:31Z
[INFO] ------------------------------------------------------------------------
```

This is what I did to the docker build script: https://github.com/neomatrix369/awesome-ai-ml-dl/blob/master/examples/tribuo/docker-image/Dockerfile#L30 and https://github.com/neomatrix369/awesome-ai-ml-dl/blob/master/examples/tribuo/docker-image/Dockerfile#L45

**Comment by neomatrix369** [comment]
```
var xgbModel = train("XGBoost",xgb,trainData);
evaluate(xgbModel,evalData);
```
gives
```
Training XGBoost took (00:00:00:375)
Evaluation (train):
  RMSE 0.143871
  MAE 0.097167
  R^2 0.968252
Evaluation (test):
  RMSE 0.599478
  MAE 0.426673
  R^2 0.447378
```

Works now.

I'll close this issue. I hope there is some useful feedback here.

**Comment by Craigacp** [comment]
There's a place on the website that discusses the native libraries we use, that has some discussion of considerations using TF, but it's not got anything about xgboost or onnx runtime. I'd like to get a windows binary upstream into xgboost, but I've not had chance to push on that yet.

**Comment by neomatrix369** [comment]
> I can't figure out the base image you're using, is it this - https://hub.docker.com/layers/valohai/jupyhai/latest/images/sha256-0ae21dee7e887c17eec73f5b04533ba48bdba896e46838d4aecf9264d52862d9?context=explore ?
> 
> Either way, we've have some dependency issues when using XGBoost in containers (see the note at the bottom of here - https://tribuo.org/learn/4.0/javadoc/org/tribuo/common/xgboost/XGBoostTrainer.html).
> 
> The libraries it expects according to ldd are:
> 
> ```
> 	linux-vdso.so.1 (0x00007ffffcff7000)
> 	libjvm.so => not found
> 	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f1a5f1ba000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1a5f197000)
> 	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1a5f18c000)
> 	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1a5efab000)
> 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1a5ee5c000)
> 	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1a5ee3f000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1a5ec4d000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f1a5f860000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1a5ec47000)
> ```
> 
> It'll pull in libjvm automatically as it's already in the process space when you load it via JNI, so I suspect it's either libc, libstdc++ or libgomp you're missing.

@Craigacp I have just updated the tribuo docker image to a new base image, see this https://hub.docker.com/layers/neomatrix369/tribuo/0.2/images/sha256-061207cd26de6de294106c923de42e4d125e669bfdb5bf9fed763eeb1e221131?context=explore 

Everything else works like it did.

**Comment by Craigacp** [comment]
Ok, so that docker image has all the right dependencies for XGBoost now?

**Comment by neomatrix369** [comment]
> Ok, so that docker image has all the right dependencies for XGBoost now?

Its does, I have demo-ed the Regression tutorial at the last presentation I gave earlier in the week.
