### ISSUE TITLE
[Docs] Discrepancy in Gradle instruction between docs on Tribuo.org and GitHub README.md

### ISSUE THREAD

**Issue by neomatrix369** [oracle/tribuo#60]
**Describe the bug**

The Gradle tab in https://tribuo.org/#gradle says:

```gradle
implementation ("org.tribuo:tribuo-all:4.0.1@pom") {
    transitive = true // for Groovy
    // isTransitive = true // for Kotlin
}
```

while the README on GitHub says:

```
api 'org.tribuo:tribuo-all:4.0.0@pom'
```

The former works in Gradle 6.5, the latter does not work, and gives the below error:

```
* What went wrong:
A problem occurred evaluating root project 'tribuo-classification'.
> Could not find method api() for arguments [org.tribuo:tribuo-all:4.0.1@pom] on object of 
type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

```

**Expected behaviour**

Both docs to refer to the same information. Also would help if there was a bit more context to the Gradle docs, i.e.:
```gradle
dependencies {
    implementation ("org.tribuo:tribuo-all:4.0.1@pom")
    ....
}
```

**Comment by Craigacp** [comment]
The latter should work if you've got `java-library` imported (aside from the fact that Gradle doesn't transitively pull in pom dependencies). Gradle's split between `api` and `implementation` is frustrating as it makes it difficult to give exact snippets because they aren't defined in the same plugin. I've updated the readme in the [docs-fixes](https://github.com/oracle/tribuo/tree/doc-fixes) branch where we're aggregating these small fixes.

**Comment by neomatrix369** [comment]
> The latter should work if you've got `java-library` imported (aside from the fact that Gradle doesn't transitively pull in pom dependencies). Gradle's split between `api` and `implementation` is frustrating as it makes it difficult to give exact snippets because they aren't defined in the same plugin. I've updated the readme in the [docs-fixes](https://github.com/oracle/tribuo/tree/doc-fixes) branch where we're aggregating these small fixes.

That's fine, for now, I'm only trying to get things to work and reporting issues whether I have a workaround or not.

Thnx for the quick response. I will try to improve on this later on.

**Comment by neomatrix369** [comment]
I have an example Gradle settings file we could link from the Docs, see https://github.com/neomatrix369/awesome-ai-ml-dl/blob/master/examples/tribuo/build.gradle

Or you could craft a pseudo/example version from this one. It an extra step of creating uberjars but that's something we can strip off if you like

**Comment by Craigacp** [comment]
My preference would be to not include example build system files in the Tribuo repo. Including them means we'd have to maintain them, keep up with best practices and deal with different gradle versions which keep changing the allowable syntax.

Your example seems to be missing the transitive flag, and it doesn't specify that it's a pom only dependency. What version of gradle does it build with?

**Comment by neomatrix369** [comment]
I understand about maintaining examples, but a minimum/basic set of config for `maven` and `gradle` would help developers build their applications, otherwise it might just result in more questions from the community.

I just added the transitive flags as docs including the `gradle` version (version 6.5)

Using:
```
implementation 'org.tribuo:tribuo-all:4.0.1@pom'
```
Does not result in a successful build, if fails with these messages:

```java
> Task :compileJava FAILED
Caching disabled for task ':compileJava' because:
  Build cache is disabled
Task ':compileJava' is not up-to-date because:
  Task has failed previously.
The input changes require a full rebuild for incremental task ':compileJava'.
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with JDK Java compiler API.
/path/to/tribuo/src/main/java/org/neomatrix369/tribuo/RegressionExample.java:7: error: package org.tribuo.data.csv does not exist
import org.tribuo.data.csv.CSVLoader;
                          ^
.
.
.
  symbol:   variable ProvenanceUtil
  location: class ClassificationExample
77 errors
:compileJava (Thread[Execution worker for ':',5,main]) completed. Took 0.719 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
```

When I used:

```
implementation 'org.tribuo:tribuo-all:4.0.1'
```
It builds fine and the example works  - do give it a whirl to see if it works for you too.


Am I missing something else for the `build.gradle` file.

**Comment by Craigacp** [comment]
You've not uncommented the appropriate transitive flag, nor put it in the braces, so it only downloads the pom and thus fails to find the other bits. It should look like this:
```groovy
implementation ("org.tribuo:tribuo-all:4.0.1@pom") {
    transitive = true
}
```

We have it as a pom dependency as otherwise the pom file that gradle generates for downstream deployment into maven repositories says that the `tribuo-all` dependency is a jar and it breaks maven projects which consume the library built with gradle.

**Comment by neomatrix369** [comment]
> You've not uncommented the appropriate transitive flag, nor put it in the braces, so it only downloads the pom and thus fails to find the other bits. It should look like this:
> 
> ```groovy
> implementation ("org.tribuo:tribuo-all:4.0.1@pom") {
>     transitive = true
> }
> ```
> 
> We have it as a pom dependency as otherwise the pom file that gradle generates for downstream deployment into maven repositories says that the `tribuo-all` dependency is a jar and it breaks maven projects which consume the library built with gradle.

Thanks, it works now.

Maybe the `// for Groovy` causes a bit of confusion - am I right if the annotation is trying to explain which flag to use depending on the gradle build script language?

**Comment by Craigacp** [comment]
We should probably change it to:
```
// for build.gradle
// for build.gradle.kts
```

I think that's how the gradle daemon figures out what kind of file it is.

**Comment by neomatrix369** [comment]
> We should probably change it to:
> 
> ```
> // for build.gradle
> // for build.gradle.kts
> ```
> 
> I think that's how the gradle daemon figures out what kind of file it is.

Cool idea, I'm adding this to my list.

**Comment by Craigacp** [comment]
Ah I meant that the filename is how gradle figures out what type it is, so hopefully the comment will help users uncomment the appropriate bit for the filename they use.

**Comment by neomatrix369** [comment]
Thanks @Craigacp for applying the feedback via your new PR.

A minor suggestion, with regards to the `gradle` settings example under the **Getting Started** tab (on https://tribuo.org/): 
```java
implementation ("org.tribuo:tribuo-all:4.0.1@pom") {
    transitive = true // for Groovy
    // isTransitive = true // for Kotlin
}
```

It would be nicer to read if the `gradle` tab was split into two tabs instead:

- `gradle (groovy)`
```java
implementation ("org.tribuo:tribuo-all:4.0.1@pom") {
    transitive = true
}
```
and

- `gradle (kotlin)`
```java
implementation ("org.tribuo:tribuo-all:4.0.1@pom") {
    isTransitive = true
}
```
What do you think?

**Comment by Craigacp** [comment]
We could, but everything else has three panes on the front page of the website so it's nicely symmetrical at the moment. I don't see a reason to break that because Gradle has multiple languages. Users of Gradle should be capable of picking the appropriate snippet for their language from the snippet.
