### ISSUE TITLE
 Scaling/Rescaling needed for regression outputs

### ISSUE THREAD

**Issue by EyalWirsansky** [oracle/tribuo#73]
**Is your feature request related to a problem? Please describe.**
Currently scaling of training data (via transformations such as MeanStdDevTransformation) only applies to the features but not to the outputs; however regression outputs need to be scaled as well for some models to train properly. Specifically, this causes the RBF SVM to perform much more poorly comparing to scikit-learn, where it's easy to scale the entire dataset.

**Describe the solution you'd like**
Adding the option to scale the output of a training dataset in addition to the features when training a regressor. This also means that the output of the regressor will be inverse-scaled when performing predictions.

**Describe alternatives you've considered**
'Manually' scaling and inverse-scaling outside Tribuo's training/prediction flow. This is cumbersome, and in addition will not be included in the provenance.

**Additional context**

**Comment by Craigacp** [comment]
Thanks for the report, there are a few ways we could integrate this support. Wrapping it via a StandardisingTrainer similar to the TransformTrainer would induce another dataset copy, whereas integrating it directly into the affected regression trainers would be a bunch more code. We'll have a look at figure out which way seems most efficient.

**Comment by Craigacp** [comment]
There's a prototype for LibSVM models here - https://github.com/oracle/tribuo/tree/regression-rescaling. We're currently trying to figure out if there is a way to build that into all regression models without too much repeated code (and even if it's necessary for things like XGBoost).

**Comment by Craigacp** [comment]
After some checking it didn't seem necessary in models other than LibSVM regressors, so we just added an option to that trainer.
