### ISSUE TITLE
How to use confusion matrix for cross validation?

### ISSUE THREAD

**Issue by nikkisingh111333** [oracle/tribuo#86]
How to use confusion matrix .for cross validation im confused by classes matrictargets OR metricId Or evaluationMETRIC ETC ETC.cant find a good model summarization after digging for 3 hours in Java DocS.guide me through please?

**Comment by Craigacp** [comment]
What do you want to use as the metric to optimize? You shouldn't need to use the confusion matrix class directly unless you are trying to maximise or minimise a specific element of the matrix. If you want to maximise precision, recall or per class versions of those metrics then you can pass in that metric target. Or just aggregate the whole lot and look at the descriptive statistics object that is related to the metric you care about.

**Comment by nikkisingh111333** [comment]
No basically i m using evalautionaggregation and passing evaluation list
..but getting metrics id and descriptive stats ..i want to be inside
confusion matrix to get clear rrsult with f1 score of each evaluation done
by k fold cv.just like in python..how can i get it.

**Comment by Craigacp** [comment]
A quick example of getting the f1 scores is as follows:
```java
CrossValidation cv = new CrossValidation(trainer,trainingDataset,new LabelEvaluator(),5);
List<Pair<LabelEvaluation,Model<Label>>> evaluations = cv.evaluate();
List<Double> f1s = evaluations.stream().map(Pair::getA).map(LabelEvaluation::macroAveragedF1).collect(Collectors.toList());
```
if you want the descriptive stats then this would work:
```java
DescriptiveStats f1Stats = EvaluationAggregator.summarize(evaluations.stream().map(Pair::getA).collect(Collectors.toList()),LabelEvaluation::macroAveragedF1);
```

**Comment by nikkisingh111333** [comment]
thanks a lot bro it helps a lot.is there any new version coming out for
tribou with better docs because there are lot of thing has to handle in
java and it needs a good documenrtations which should cover most of the
important features and parts and 'HOW TO DO's' in java.because most of the
devs specially my friends are not handy in new java syntax.i m considering
to implement tribou in my web app for production just small ml projects so
good documentations will surely help me?

**Comment by Craigacp** [comment]
There is a documentation update for the website with the extra javadocs and tutorials from 4.0.2 here - https://github.com/oracle/tribuo-site/pull/4. We'll merge it in to update the website once the 4.0.2 binaries are live on Maven Central, which should be this week or early next week.

We can add more documentation for the cross validation and evaluation aggregators as those are currently underdocumented, but we're doing this alongside new feature development and bug fixes, all of which take time. If you want to contribute to the docs we're happy to accept pull requests that improve them.

**Comment by nikkisingh111333** [comment]
i appreciate it ...i m too excited for NEW ml features from tribou and
looking ahead from sklearn hope many will use java for ml in upcoming
years..
