### ISSUE TITLE
Datapreprocessing stuffs ?

### ISSUE THREAD

**Issue by nikkisingh111333** [oracle/tribuo#95]
hey today i have seen my friend using SMOT for imbalanced dataset a KNN type of algorithm for managing imbalanced data samples .its super easy in python and maintain dataset information with ratio.How can i do same kind of tricks in tribuo without touching any GUI tools tableau or rapidminer. there are more other tricks i found today:

- random oversampling

- Vectorization of longtext data
 
how can i do them in tribou ?
or alternatives you suggest? for same

**Comment by Craigacp** [comment]
We don't have an implementation of SMOTE, we tend to use example weighting to deal with imbalanced classes, and XGBoost has worked extremely well for that (we've deployed it in production on a severely imbalanced problem).

Oversampling can be achieved using a user supplied function to generate the indices supplied to a `DatasetView`. This is similar to how we create the boostraps in [`BaggingTrainer`](https://github.com/oracle/tribuo/blob/eb915d7b29710493e8a1eeefe1342bb12edf5b0d/Core/src/main/java/org/tribuo/ensemble/BaggingTrainer.java#L138) or the resampling in [`AdaBoostTrainer`](https://github.com/oracle/tribuo/blob/eb915d7b29710493e8a1eeefe1342bb12edf5b0d/Classification/Core/src/main/java/org/tribuo/classification/ensemble/AdaBoostTrainer.java#L172). The `AdaBoostTrainer` creates a weighted bootstrap sample, which in practice oversamples difficult examples and undersamples easy examples (as defined by the AdaBoost.SAMME algorithm).

Tribuo comes with a built in text pipeline that can create a bag of words representation with term counting in [`TokenPipeline`](https://github.com/oracle/tribuo/blob/main/Data/src/main/java/org/tribuo/data/text/impl/TokenPipeline.java). If you want to convert that into TF-IDF then you could use the `org.tribuo.transform` infrastructure, write a custom transformer to calculate IDF, and then rescale all the term count features by the IDF (by applying the transformation). Writing custom transformers is a little tricky, but this one should be fairly straightforward. The transformation infrastructure is briefly discussed in the [configuration tutorial](https://tribuo.org/learn/4.0/tutorials/configuration-tribuo-v4.html#Feature-Transformations).

**Comment by nikkisingh111333** [comment]
so in a nutsell you are basically saying that imbalanced data automatically managed under several algorithm we do no need to do much effort for it.that what you are saying ?.

**Comment by Craigacp** [comment]
For `Trainer`s which implement `org.tribuo.WeightedExamples` then I'd try setting appropriate example weights on the training dataset before building the model instead of performing oversampling. Oversampling loses some information and the reweighting doesn't. If the trainer you want doesn't support that then you can perform oversampling by generating your own indices and constructing a `org.tribuo.dataset.DatasetView` then use that as the training dataset.

**Comment by nikkisingh111333** [comment]
Thanks, I'll check it out. Good m
